### ISSUE TITLE
.NET 2 required error on 2012 R2

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gpfjeff/winhasher#9]
```
What steps will reproduce the problem?
1. Install Microsoft Windows Server 2012 R2, e.g.:
a) Download 2012 R2 Trial:
   http://technet.microsoft.com/en-us/evalcenter/dn205286.aspx
   or
b) Start an Amazon EC2 Microsoft Windows Server 2012 R2 Micro Instance
   http://aws.amazon.com/windows/amis/
   http://aws.amazon.com/free/
2. Check .NET versions installed, e.g.:
   dir %WINDIR%\Microsoft.Net\Framework\v* /O:-N /B
   v4.0.30319
   v2.0.50727
   v1.1.4322
   v1.0.3705
3. Install Winhasher
https://code.google.com/p/winhasher/

What is the expected output? What do you see instead?
- Successful installation.
- Setup error:
  "The Microsoft .NET Framework version 2.0 or higher is required to run
   this application, but I couldn't find it installed on your system. Would
   you like to download it now?"
 
What version of the product are you using? On what operating system?
- Current Release 1.6.2.67.
- Windows Server 2012 R2 Standard Build 9600 (RTM)

Please provide any additional information below.
- Works great on Windows 7 Ultimate SP1 (64-bit).
```

Original issue reported on code.google.com by `ray...@netro.com.au` on 12 Jun 2014 at 10:18

Attachments:
* [winhasher - NET 2 required - Jun 14.png](https://storage.googleapis.com/google-code-attachments/winhasher/issue-9/comment-0/winhasher - NET 2 required - Jun 14.png)

**Comment by gpfjeff** [comment]
I realize it's been a long time since this issue has been updated, but I haven't received a response from the original report either. According to the following Microsoft sites, we're using the correct, valid techniques for determining the existence of .NET 2.0 (that is, looking in the system registry):

https://msdn.microsoft.com/en-us/library/hh925568(v=vs.110).aspx
https://support.microsoft.com/en-us/kb/318785

Since the original reporter never responded, I have to assume that either he or she successfully installed WinHasher by downloading the binaries sans the installer, or gave up. Since the links above seem to indicate we're doing the right detection method, I'm going to close this issue.
